const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('hangar', {
  // ドロップされた File の実パスを取得。Electron 42 では File.path が廃止のため webUtils を使う。
  getPathForFile: (file) => { try { return webUtils.getPathForFile(file) || ''; } catch { return (file && file.path) || ''; } },
  isDirectory: (p) => ipcRenderer.invoke('is-directory', p),
  pickFolder: (opts) => ipcRenderer.invoke('pick-folder', opts),
  scan: (folder) => ipcRenderer.invoke('scan', folder),
  detect: (folders) => ipcRenderer.invoke('detect', folders),
  regen: () => ipcRenderer.invoke('regen'),
  rescan: () => ipcRenderer.invoke('rescan'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  render: (target) => ipcRenderer.invoke('render', target),
  catalogExists: () => ipcRenderer.invoke('catalog-exists'),
  catalogUrl: () => ipcRenderer.invoke('catalog-url'),
  capabilities: () => ipcRenderer.invoke('render-capabilities'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  pickFile: () => ipcRenderer.invoke('pick-file'),
  diff: (pkg, project) => ipcRenderer.invoke('diff', pkg, project),
  compare: (projects) => ipcRenderer.invoke('compare', projects),
  listProjects: () => ipcRenderer.invoke('list-projects'),
  sprawl: () => ipcRenderer.invoke('sprawl'),
  reclaimPreview: () => ipcRenderer.invoke('reclaim-preview'),
  reclaimWrite: (outDir) => ipcRenderer.invoke('reclaim-write', outDir),
  saveTemplate: (projectDir, outDir) => ipcRenderer.invoke('save-template', projectDir, outDir),
  restoreTemplate: (templateDir, projectDir, force) => ipcRenderer.invoke('restore-template', templateDir, projectDir, force),
  importAe: (dir, scan) => ipcRenderer.invoke('import-ae', dir, scan),
  boothEnrichAll: () => ipcRenderer.invoke('booth-enrich-all'),
  onStatus: (cb) => ipcRenderer.on('status', (_e, m) => cb(m)),
  onCatalogUrl: (cb) => ipcRenderer.on('catalog-url', (_e, u) => cb(u)),
});
